name: Gambit
version: '${project.version}'
main: me.opd.gambit.GambitPlugin
authors: [ opd02 ]
api-version: 1.20
description: Custom gamemode of banking orbs, bosses, and evolved pvp
commands:
  gteam:
  setup:
  start:
  tokengive:
  gabort: